### ISSUE TITLE
Support for Desktop and Web

### ISSUE THREAD

**Issue by JagadishaIncture** [ChainTechNetwork/ComposeMultiplatformMediaPlayer#2]

**Comment by ctn-mobile-innovation** [comment]
Hello @JagadishaIncture 

For now we don't have support for this, but we are planning to add same in upcoming version!

**Comment by JagadishaIncture** [comment]
@ctn-mobile-innovation  any updates for web

**Comment by jaredsburrows** [comment]
@ctn-mobile-innovation Why close this issue? Let's leave it open to track the progress.

**Comment by luca992** [comment]
@ctn-mobile-innovation Is the a reason for not supporting the js target and only wasmJs?
