### ISSUE TITLE
Is this library open source?

### ISSUE THREAD

**Issue by jakoss** [ChainTechNetwork/ComposeMultiplatformMediaPlayer#3]
Is this library open source?

**Comment by ctn-mobile-innovation** [comment]
Hello @jakoss 

Yes it is!

**Comment by jakoss** [comment]
But.. Where can I see it? In this repo there is only an example code

**Comment by vickyleu** [comment]
@jakoss i decompile player source file to kotlin code, you can use, [ComposeMultiplatformMediaPlayer](https://github.com/vickyleu/ComposeMultiplatformMediaPlayer)

**Comment by jakoss** [comment]
I don't want to decompile it, i want to see the source. The author claims this is open source library 😆

**Comment by justjanne** [comment]
> I don't want to decompile it, i want to see the source. The author claims this is open source library 😆

The author did publish the source – but only as sources jar on maven, which is obviously not very useful. I gathered all the sources jars and combined them into a new repository: https://github.com/justjanne/ComposeMultiplatformMediaPlayer/

**Comment by MrJohn10** [comment]
Reported this repo for falsely claiming it's open sourced.
